// Objective-C API for talking to github.com/wpajqz/linker/export Go package.
//   gobind -lang=objc github.com/wpajqz/linker/export
//
// File is generated by gobind. Do not edit.

#ifndef __Export_H__
#define __Export_H__

@import Foundation;
#include "Universe.objc.h"


@class ExportClient;
@protocol ExportErrorHandler;
@class ExportErrorHandler;
@protocol ExportHandler;
@class ExportHandler;
@protocol ExportRequestStatusCallback;
@class ExportRequestStatusCallback;

@protocol ExportErrorHandler <NSObject>
- (void)handle:(NSString*)err;
@end

@protocol ExportHandler <NSObject>
- (void)handle:(NSData*)header body:(NSData*)body;
@end

@protocol ExportRequestStatusCallback <NSObject>
- (void)onEnd;
- (void)onError:(long)status message:(NSString*)message;
- (void)onStart;
- (void)onSuccess:(NSData*)header body:(NSData*)body;
@end

@interface ExportClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init:(NSString*)server port:(long)port;
/**
 * 添加事件监听器
 */
- (void)addMessageListener:(NSString*)listener callback:(id<ExportHandler>)callback;
/**
 * 向服务端发送请求，异步处理服务端返回结果
 */
- (void)asyncSend:(NSString*)operator param:(NSData*)param callback:(id<ExportRequestStatusCallback>)callback;
/**
 * 获取请求属性
 */
- (NSString*)getRequestProperty:(NSString*)key;
/**
 * 获取响应属性
 */
- (NSString*)getResponseProperty:(NSString*)key;
/**
 * 链接断开以后执行回收操作
 */
- (void)onClose:(id<ExportHandler>)handler;
/**
 * 设置默认错误处理方法
 */
- (void)onError:(id<ExportErrorHandler>)errorHandler;
/**
 * 链接建立以后执行的操作
 */
- (void)onOpen:(id<ExportHandler>)handler;
/**
 * 心跳处理，客户端与服务端保持长连接
 */
- (void)ping:(int64_t)interval param:(NSData*)param callback:(id<ExportRequestStatusCallback>)callback;
/**
 * 移除事件监听器
 */
- (void)removeMessageListener:(NSString*)listener;
/**
 * 设置请求属性
 */
- (void)setRequestProperty:(NSString*)key value:(NSString*)value;
/**
 * 设置响应属性
 */
- (void)setResponseProperty:(NSString*)key value:(NSString*)value;
/**
 * 设置断线重连的间隔时间, 单位s
 */
- (void)setRetryInterval:(long)interval;
/**
 * 设置服务端默认超时时间, 单位s
 */
- (void)setTimeout:(long)timeout;
/**
 * 向服务端发送请求，同步处理服务端返回结果
 */
- (void)syncSend:(NSString*)operator param:(NSData*)param callback:(id<ExportRequestStatusCallback>)callback;
@end

FOUNDATION_EXPORT const int64_t ExportMaxPayload;

FOUNDATION_EXPORT ExportClient* ExportNewClient(NSString* server, long port);

@class ExportErrorHandler;

@class ExportHandler;

@class ExportRequestStatusCallback;

@interface ExportErrorHandler : NSObject <goSeqRefInterface, ExportErrorHandler> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)handle:(NSString*)err;
@end

@interface ExportHandler : NSObject <goSeqRefInterface, ExportHandler> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)handle:(NSData*)header body:(NSData*)body;
@end

@interface ExportRequestStatusCallback : NSObject <goSeqRefInterface, ExportRequestStatusCallback> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onEnd;
- (void)onError:(long)status message:(NSString*)message;
- (void)onStart;
- (void)onSuccess:(NSData*)header body:(NSData*)body;
@end

#endif
