
// Objective-C API for talking to the following Go packages
//
//	github.com/wpajqz/linker/export
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Export_FRAMEWORK_H__
#define __Export_FRAMEWORK_H__

#include "Export.objc.h"
#include "universe.objc.h"

#endif
